### ISSUE TITLE
Resource network_interface, subnet hangs in loop on "Still creating..."

### ISSUE THREAD

**Issue by steevaavoo** [steevaavoo/azure-terraform#5]
https://github.com/terraform-providers/terraform-provider-azurerm/issues/2758

We are seeing this issue. Will attempt the Workaround the author describes.

**Comment by steevaavoo** [comment]
The workaround - specifically the delay resource - doesn't work for me, possibly due to the OS I'm running from (speculation).

What I've discovered is that, if I _either_ run using the nested assignments of NSGs (`network_security_group_id`) _or_ run the _new_ `resource "azurerm_subnet_network_security_group_association"`, it works without hangs. However the `resource "azurerm_subnet_network_security_group_association"` has the interesting issue where it blanks/refills the subnet name on alternative `terraform apply` runs.

For now I've commented out the _new_ method in favour of the older, nested method.

**Comment by Dmitry1987** [comment]
it is still the case, was it fixed (infinite loop), or the only solution is migrate to provider 2.0? 
if I comment out "azurerm_subnet_network_security_group_association" and create, all ok, then uncomment and "add on top".  But if it's active on first run, gets in a loop.

**Comment by steevaavoo** [comment]
Hi Dmitry. I'm afraid I haven't looked at this for over a year and can't even remember the project! But I'm aware that there is a new major version (2.7.0) so it may well be handled there.
